# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

SCANCODE_SOURCE_NAME = "SC"
SCANCODE_SOURCE_NAME_DEPENDENCY = "SC-D"
SCANCODE_SOURCE_NAME_PACKAGE = "SC-P"
SCANCODE_PRIORITY = 50
SCANCODE_DEPENDENCY_PRIORITY = 40
SCANCODE_PACKAGE_PRIORITY = 30
