# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0
import logging

from deepdiff import DeepDiff

from opossum_lib.core.entities.base_url_for_sources import BaseUrlsForSources
from opossum_lib.core.entities.config import Config
from opossum_lib.core.entities.external_attribution_source import (
    ExternalAttributionSource,
)
from opossum_lib.core.entities.frequent_license import FrequentLicense
from opossum_lib.core.entities.metadata import Metadata
from opossum_lib.core.entities.opossum import Opossum
from opossum_lib.core.entities.opossum_package import OpossumPackage
from opossum_lib.core.entities.root_resource import RootResource
from opossum_lib.core.entities.scan_results import ScanResults
from opossum_lib.shared.entities.opossum_output_file_model import OpossumOutputFileModel


def compare_impl(first: Opossum, second: Opossum) -> None:
    _compare_scan_results(first.scan_results, second.scan_results)
    _compare_review_results(first.review_results, second.review_results)


def _compare_scan_results(first: ScanResults, second: ScanResults) -> None:
    _compare_metadata(first.metadata, second.metadata)
    _compare_attribution_breakpoints(
        first.attribution_breakpoints, second.attribution_breakpoints
    )
    _compare_configs(first.config, second.config)
    _compare_frequent_licenses(first.frequent_licenses, second.frequent_licenses)
    _compare_files_with_children(first.files_with_children, second.files_with_children)
    _compare_base_urls_for_sources(
        first.base_urls_for_sources, second.base_urls_for_sources
    )
    _compare_attribution_to_id(first.attribution_to_id, second.attribution_to_id)
    # _compare_unassigned_attributions(first.unassigned_attributions,
    # second.unassigned_attributions)
    _compare_external_attribution_sources(
        first.external_attribution_sources, second.external_attribution_sources
    )
    _compare_resources(first.resources, second.resources)


def _compare_attribution_breakpoints(first: list[str], second: list[str]) -> None:
    first_set = set(first)
    second_set = set(second)
    if first_set != second_set:
        diff_result = DeepDiff(first_set, second_set)
        logging.error(f"Differences between attribution breakpoints: \n {diff_result}")
    else:
        logging.info("No differences between attribution breakpoints")


def _compare_configs(first: Config, second: Config) -> None:
    diff = DeepDiff(first, second)
    if diff != {}:
        logging.error(f"Differences between configs: \n {diff}")
    else:
        logging.info("No differences between configs")


def _compare_frequent_licenses(
    left: list[FrequentLicense], right: list[FrequentLicense]
) -> None:
    diff = DeepDiff(left, right)
    if diff != {}:
        logging.error(f"Differences between frequent licenses {diff}")
    else:
        logging.info("No differences between frequent licenses")


def _compare_files_with_children(first: list[str], second: list[str]) -> None:
    first_set = set(first)
    second_set = set(second)
    if first_set != second_set:
        diff_result = DeepDiff(first_set, second_set)
        logging.error(f"Differences between files with children: \n {diff_result}")
    else:
        logging.info("No differences between files with children")


def _compare_base_urls_for_sources(
    first: BaseUrlsForSources, second: BaseUrlsForSources
) -> None:
    diff = DeepDiff(first, second)
    if diff != {}:
        logging.error(f"Differences between base urls for sources: {diff}")
    else:
        logging.info("No differences between base urls for sources")


def _compare_attribution_to_id(
    first: dict[OpossumPackage, str], second: dict[OpossumPackage, str]
) -> None:
    # The attributions are autogenerated or stem from the input file,
    # not really comparable
    # Compare only the packages will be handled from the resource tree
    # nothing to do here
    pass


def _compare_unassigned_attributions(
    first: set[OpossumPackage], second: set[OpossumPackage]
) -> None:
    first_size = len(first)
    second_size = len(second)
    if first_size != second_size:
        logging.error(
            f"Differences between unassigned attributions,"
            f" {first_size} != {second_size}"
        )
    if first == second:
        logging.info("No differences between unassigned attributions")
    else:
        diff = DeepDiff(first, second)
        logging.error(
            f"Differences between unassigned attributions: \n {diff.to_json()}"
        )


def _compare_external_attribution_sources(
    first: dict[str, ExternalAttributionSource],
    second: dict[str, ExternalAttributionSource],
) -> None:
    diff = DeepDiff(first, second)
    if diff != {}:
        logging.error(
            f"Differences between external attribution sources:\n {diff.to_json()}"
        )
    else:
        logging.info("No differences between external attribution sources")


def _compare_resources(first: RootResource, second: RootResource) -> None:
    first_paths = set(resource.path for resource in first.all_resources())
    second_paths = set(resource.path for resource in second.all_resources())
    path_diff = DeepDiff(first_paths, second_paths)
    if path_diff != {}:
        logging.error(f"Differences between resources path: {path_diff.to_json()}")
    else:
        logging.info("No differences between resources")


def _compare_metadata(first: Metadata, second: Metadata) -> None:
    diff_result = DeepDiff(first, second)
    if diff_result != {}:
        logging.error(f"Different metadata: {diff_result}")
    else:
        logging.info("Metadata is identical")


def _compare_review_results(
    first: OpossumOutputFileModel | None, second: OpossumOutputFileModel | None
) -> None:
    if first is None and second is None:
        logging.info("Both files do not contain review results")
    elif first is not None and second is not None:
        logging.info(
            "Both files contain review results,"
            " no further comparison implemented at this point"
        )
    elif first is None and second is not None:
        logging.error("Only the first file contains review results")
    else:
        logging.error("Only the second file contains review results")
