# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Build Executable
on:
  push:
    branches:
      - main
      - 'renovate/*'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  linter:
    runs-on: ${{ matrix.os }}
    if: |
      !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/'))
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --locked

      - name: Install PyInstaller
        run: uv pip install pyinstaller

      - name: Build executable
        run: uv run pyinstaller --onefile --add-data ".venv/lib/python3.13/site-packages/license_expression/data/scancode-licensedb-index.json:./license_expression/data" --add-data ".venv/lib/python3.13/site-packages/spdx_tools/spdx/parser/tagvalue/parser.out:./spdx_tools/spdx/parser/tagvalue" src/opossum_lib/cli.py
      
      - name: Test executable
        run: dist/cli --help
